# https://golangci-lint.run/docs/configuration/file/
# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
version: "2"
run:
  timeout: 1m
  build-tags:
    - examples
    - integration

linters:
  default: standard # https://github.com/golangci/golangci-lint/blob/60180aacaa642385a3f683875507013b43214edf/.golangci.reference.yml#L14
  enable:                       # golangci-lint help linters
    - asasalint                 # check for pass []any as any in variadic func(...any)
    - bidichk                   # hecks for dangerous unicode character sequences
    - contextcheck              # check whether the function uses a non-inherited context
    - copyloopvar               # detects places where loop variables are copied
    - decorder                  # check declaration order and count of types, constants, variables and functions
    - depguard                  # checks if package imports are in a list of acceptable packages
    - fatcontext                # detects nested contexts in loops and function literals
    - forbidigo                 # forbids identifiers
    - forcetypeassert           # find forced type assertions
    - gocheckcompilerdirectives # checks that go compiler directive comments (//go:) are valid
#    - gochecknoglobals          # check that no global variables exist
#    - gochecknoinits            # checks that no init functions are present in Go code
    - gocritic                  # provides diagnostics that check for bugs, performance and style issues
    - godoclint                 # checks Golang's documentation practice (godoc)
    - godot                     # check if comments end in a period
    - gomodguard_v2             # allow and blocklist linter for direct Go module dependencies
    - gosec                     # inspects source code for security problems
    - gosmopolitan              # report certain i18n/l10n anti-patterns
    - makezero                  # find slice declarations with non-zero initial length
    - modernize                 # a suite of analyzers that suggest simplifications to Go code, using modern language and library features
    - perfsprint                # checks that fmt.Sprintf can be replaced with a faster alternative
    - prealloc                  # find slice declarations that could potentially be pre-allocated
    - reassign                  # checks that package variables are not reassigned
    - revive                    # fast, configurable, extensible, flexible, and beautiful linter
    - thelper                   # thelper detects tests helpers which do not start with the t.Helper() method
  settings:
    depguard:
      rules:
        production_whitelist:
          list-mode: strict
          files:
            - "$all"
            - "!$test"                   # exclude *_test.go files
            - "!**/examples/**/main.go"  # exclude ./examples/**/main.go
          allow:
            - context
            - io
            - os
            - os/signal
            - strconv
            - sync
            - sync/atomic
            - syscall
            - time
            - unique
            - unsafe  # used in fraction.go
            - github.com/hashicorp/golang-lru/v2
            - golang.org/x/term
        test_whitelist:
          list-mode: strict
          files:
            - "$test"   # include *_test.go files
            - "!**/integration_test.go"
          allow:
            - bytes
            - context
            - errors
            - fmt
            - io
            - math
            - os
            - reflect
            - runtime
            - strconv
            - strings
            - sync
            - sync/atomic
            - syscall
            - testing
            - time
            - unicode/utf8
            - github.com/google/go-cmp/cmp
            - github.com/google/go-cmp/cmp/cmpopts
        integration_test_whitelist:
          list-mode: strict
          files:
            - "**/integration_test.go"
          allow:
            - flag
            - fmt
            - io
            - math/rand/v2
            - os
            - path/filepath
            - runtime
            - slices
            - strconv
            - strings
            - sync
            - testing
            - time
            - unsafe
        examples_whitelist:
          list-mode: strict
          files:
            - "**/examples/**/main.go"
          allow:
            - context
            - fmt
            - math/rand/v2
            - os
            - os/signal
            - syscall
            - time
            - github.com/jbunds/progress
