# https://golangci-lint.run/docs/configuration/file/
# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
version: "2"
run:
  timeout: 1m

linters:
  default: standard # https://github.com/golangci/golangci-lint/blob/60180aacaa642385a3f683875507013b43214edf/.golangci.reference.yml#L14
  enable:
    - bodyclose
    - canonicalheader
    - contextcheck
    - decorder
    - gocritic
    - godoclint
    - gosec
    - revive
