# https://pre-commit.com
# https://github.com/pre-commit/pre-commit-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
      - id:    check-yaml                             # https://github.com/pre-commit/pre-commit-hooks#check-yaml
        files: \.ya?ml$
  - repo: https://github.com/golangci/golangci-lint   # https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
    rev:  v2.13.1
    hooks:
      - id:    golangci-lint
        entry: golangci-lint run --verbose            # or `go run github.com/golangci/golangci-lint/cmd/golangci-lint run`
  - repo: https://github.com/mpalmer/action-validator # https://github.com/mpalmer/action-validator#using-pre-commit
    rev:  v0.9.0
    hooks:
      - id: action-validator
  - repo: local
    hooks:
      - language:       system
        id:             go-test
        name:           go test
        entry:          go test -race -count=100 -gcflags=-d=checkptr ./...
        files:          \.go$|^go\.(?:mod|sum)$
        pass_filenames: false
        require_serial: true
