name: deploy coverage report to Pages
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
  workflow_dispatch: # allows this workflow to be manually triggered from the UI

jobs:
  deploy-coverage-report:
    uses: jbunds/coverage/.github/workflows/pages.yml@v1
