name: vuln check

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
  workflow_dispatch: # allows this workflow to be manually triggered from the UI

jobs:
  govulncheck:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7 # http://github.com/actions/checkout; v6 enforces secure credential storage under $RUNNER_TEMP
      - uses: actions/setup-go@v6 # http://github.com/actions/setup-go
        with:
          go-version-file: go.mod # https://github.com/actions/setup-go/blob/main/docs/advanced-usage.md#using-the-go-version-file-input
      - uses: golang/govulncheck-action@v1 # https://github.com/golang/govulncheck-action
        with:
          repo-checkout:    false  # uses actions/checkout@v4 under the hood, which stores credentials insecurely, so GitHub creds can be stolen via the .git/config file
          go-version-input: ''     # clear the hardcoded default to force falling back to go-version-file to resolve the Go version
          go-version-file:  go.mod # https://github.com/golang/govulncheck-action
